#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
stage-5 — make Doubao actually *visible* in the preferences UI.

The bundle already carried `id: "doubao"` inside WEBCHAT_TARGETS (stage-4,
patch_doubao_target.py), and the Model dropdown is generated by iterating that
array (llmforzotero.js ~273028) with no filtering. What the card around that
dropdown is missing is a Doubao-shaped icon, so the row resolves to nothing and
the option is invisible when you go looking for it:

  1. content/icons/providers/doubao.svg      does not exist
  2. preferences.xhtml has no
     `.llm-pref-row-icon--preset-doubao` background rule
  3. the `iconModifier` map (~266161) has no `doubao` key

Nothing errors when any of these is missing, which is what makes it ship
silently: the provider works, it just has no face.

Usage
-----
    patch_doubao_ui.py [path-to-llmforzotero.js]

The bundle path is optional. apply.py exports ZOTERO_WORKDIR and invokes every
patch the same way -- environment only, no argv -- so this script used to abort
with "usage:" when run through the orchestrator, even though it worked when
invoked by hand. That made the Doubao icon silently absent from every build.
An explicit path still wins, so running it by hand against a checkout keeps
working.
"""
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
# apply.py exports ZOTERO_WORKDIR and runs the patches there; running by hand
# from a checkout works the same way. Try the scratch dir first.
_WORKDIR = os.environ.get("ZOTERO_WORKDIR") or HERE
SRC = os.path.join(_WORKDIR, "zotero-llm-src", "xpi", "content", "scripts", "llmforzotero.js")

MARKER = 'doubao: "preset-doubao"'

# a flat monochrome glyph, kept in line with the neighbouring provider marks
DOUBAO_SVG = (
    '<svg height="1em" style="flex:none;line-height:1" viewBox="0 0 24 24"\n'
    ' width="1em" xmlns="http://www.w3.org/2000/svg">'
    '<title>Doubao</title>'
    '<path d="M4 3h16c1.65 0 3 1.35 3 3v8c0 1.65-1.35 3-3 3h-6.5L9 21v-4H4'
    'c-1.65 0-3-1.35-3-3V6c0-1.65 1.35-3 3-3z"/></svg>\n'
)

XHTML_RULE = (
    '    .llm-pref-panel .llm-pref-row-icon--preset-doubao {\n'
    '    background-image:\n'
    '    url("chrome://llmforzotero/content/icons/providers/doubao.svg"); }\n'
)

OLD_ICON_MAP_TAIL = '            gemini: "preset-gemini"\n          };'

# Upstream re-indents this block between releases (3.9.9.x shipped the rule
# with four leading spaces, 3.9.10 emits it flush against the previous "}"),
# so matching the indentation literally made this patch fail on the newer
# build even though the rule itself was still there. Anchor on the part that
# has not changed -- the gemini icon URL and its closing brace.
XHTML_GEMINI_RULE_RE = re.compile(
    r'\.llm-pref-panel\s+\.llm-pref-row-icon--preset-gemini\s*\{\s*'
    r'background-image:\s*'
    r'url\("chrome://llmforzotero/content/icons/providers/gemini\.svg"\);\s*\}'
)


def resolve_paths(bundle):
    """`llmforzotero.js` lives at <content>/scripts/, assets at <content>/."""
    content = os.path.dirname(os.path.dirname(os.path.abspath(bundle)))
    return (
        os.path.join(content, "icons", "providers", "doubao.svg"),
        os.path.join(content, "preferences.xhtml"),
    )


def ensure_icon(path):
    if os.path.exists(path) and os.path.getsize(path) > 0:
        print("  = doubao.svg already present")
        return
    with io.open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(DOUBAO_SVG)
    print("  + doubao.svg")


def patch_panel(path):
    if not os.path.exists(path):
        print("  - preferences.xhtml not found, skipped")
        return
    with io.open(path, encoding="utf-8", newline="") as fh:
        text = fh.read()
    if "preset-doubao" in text:
        print("  = preferences.xhtml already styles preset-doubao")
        return
    match = XHTML_GEMINI_RULE_RE.search(text)
    if not match:
        sys.exit("FAIL: preset-gemini rule not found in preferences.xhtml")
    end = match.end()
    # Keep whatever separator the file already uses between rules so the
    # stylesheet's own formatting is not disturbed.
    text = text[:end] + "\n" + XHTML_RULE.rstrip("\n") + text[end:]
    with io.open(path, "w", encoding="utf-8", newline="") as fh:
        fh.write(text)
    print("  ~ preferences.xhtml: preset-doubao background")


def patch_bundle(path):
    with io.open(path, encoding="utf-8", newline="") as fh:
        code = fh.read()
    if MARKER in code:
        print("  = bundle already maps doubao -> preset-doubao")
        return
    if OLD_ICON_MAP_TAIL not in code:
        sys.exit("FAIL: iconModifier tail not found in bundle")
    if code.count(OLD_ICON_MAP_TAIL) != 1:
        sys.exit("FAIL: iconModifier tail not unique (%d)"
                 % code.count(OLD_ICON_MAP_TAIL))
    code = code.replace(OLD_ICON_MAP_TAIL,
                        '            gemini: "preset-gemini",\n'
                        '            doubao: "preset-doubao"\n          };', 1)
    with io.open(path, "w", encoding="utf-8", newline="") as fh:
        fh.write(code)
    print("  ~ bundle: iconModifier gains doubao")


def main():
    bundle = sys.argv[1] if len(sys.argv) > 1 else SRC
    if not os.path.exists(bundle):
        sys.exit("FAIL: bundle not found -> %s" % bundle)

    icon_path, panel_path = resolve_paths(bundle)
    ensure_icon(icon_path)
    patch_panel(os.path.normpath(panel_path))
    patch_bundle(bundle)
    print("patched OK")


if __name__ == "__main__":
    main()
